# Config written on Sun Jan 10 19:17:32 +0100 CET 2021
[InfluxDb]
  Organization = "fumeping"
  BucketSyntax = "stats-%s"
  ServerUrl = "http://localhost:8086/"
  AuthEnabled = true
  Username = "admin"
  Password = "mycrazypassword"

[[Destinations]]
  Host = "mycustomhost"
  Interval = 60000000000
  PacketInterval = 100000000
  Count = 10
  Timeout = 10000000000
  PacketSize = 0

[[Destinations]]
  Host = "yetanothercustomhost"
  Interval = 60000000000
  PacketInterval = 100000000
  Count = 10
  Timeout = 10000000000
  PacketSize = 0
