# FumePing Config written on Mon Jan 11 17:00:47 +0100 CET 2021
influxdb:
    serverurl: http://localhost:8086/
    organization: fumeping
    defaultbucket: fumeping
    username: admin
    password: mycrazypassword
    retentionperiodhours: 168
    gatherinterval: 30
pingmonitor:
    timeout: 10
    pinginterval: 1
    payloadsize: 56
    destinations:
        First:
            host: mycustomhost
            network: ""
        Second:
            host: mycustomipv6host
            network: ip6
