# Config written on Mon Jan 11 10:46:09 +0100 CET 2021
[InfluxDb]
  DatabaseName = "fumeping"
  ServerUrl = "http://localhost:8086/"
  AuthEnabled = true
  Username = "admin"
  Password = "mycrazypassword"
  GatherInterval = 30

[PingMonitor]
  Timeout = 10
  PingInterval = 1
  PayloadSize = 56
  [PingMonitor.Destinations]
    [PingMonitor.Destinations.First]
      Host = "mycustomhost"
      Network = ""
    [PingMonitor.Destinations.Second]
      Host = "mycustomipv6host"
      Network = "ipv6"
