name: Build and Deploy job
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest]
        compile-os-arch: ["GOOS=linux GOARCH=amd64", "GOOS=linux GOARCH=386", "GOOS=linux GOARCH=arm64", "GOOS=linux GOARCH=arm", "GOOS=windows GOARCH=amd64", "GOOS=windows GOARCH=386"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build script
        run: ${{ matrix.compile-os-arch }} ./build.sh
      - name: Upload build artifacts
        if: ${{ matrix.go-version == '1.15.x' }}
        uses: actions/upload-artifact@v2
        with:
          name: BuildArtifact
          path: ./bin/fumeping*
  docker_build_deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create bin directory
        run: mkdir -p ./bin/
      - name: Download required artifacts
        uses: actions/download-artifact@v2
        with:
          name: BuildArtifact
          path: ./bin/
      - name: Filter out correct binary
        run: mv fumeping-*-linux-amd64 fumeping
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm,linux/386
          push: ${{ github.event_name == 'push' && github.ref == 'main' }}
          context: .
          file: ./build/package/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: mmichaelb/fumeping/fumeping-image
          tag_with_ref: true
