on: [push, pull_request]
name: Build Job
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest]
        compile-os-arch: ["GOOS=linux GOARCH=amd64", "GOOS=linux GOARCH=386", "GOOS=linux GOARCH=arm64", "GOOS=linux GOARCH=arm", "GOOS=windows GOARCH=amd64", "GOOS=windows GOARCH=386"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build script
        run: ${{ matrix.compile-os-arch }} ./build.sh
      - name: Upload build artifacts
        if: ${{ matrix.go-version == '1.15.x' }}
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: ./bin/fumeping*
